homepage/urls.py
from django.urls import path
from . import views
app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index")
]

payplan/urls.py
from django.urls import path

from . import views

app_name = 'payplan'
urlpatterns = [
    path('', views.index, name="index"),
    path('select', views.select_payplan, name="select"),
    path('add', views.add_payplan, name="add"),
    path('add/scaling', views.add_level, name="add-level"),
    path('edit', views.add_level, name="edit"),
    path('edit/<int:pk>', views.update_payplan, name="update"),
    path('flat', views.add_flat, name="flat"),
    path('volume-bonus', views.add_volume_bonus, name="volume-bonus")
]

paytracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls")),
    path('payplan/', include("payplan.urls")),
    path('users/', include("users.urls")),
    path('saletracker/', include("saletracker.urls"))
]

saletracker/urls.py
from django.urls import path
from . import views

app_name = 'saletracker'

urlpatterns = [
    path("", views.index, name="index"),
    path('log', views.log, name="log"),
    path('<int:pk>', views.remove_log, name="log_delete")
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('register', views.register_view, name="register")
]

saletracker/models.py
from django.db import models

# Create your models here.

saletracker/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from payplan.models import Sale, Payplan, VolumeBonus, Flat
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.db.models import Sum, Avg
from django import forms
from django.shortcuts import redirect
from payplan.forms import DateForm
import datetime
from datetime import datetime

class LogSaleForm(forms.Form):
    profit = forms.IntegerField(label="Profit")

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    current_user = request.user
    if not Sale.objects.filter(salecredit=current_user).exists():
        return render(request, "saletracker/index.html", {
            "message": "No sales logged",
            "form": LogSaleForm(),
            "date": DateForm()

        })
    if request.method == "POST":
        form = DateForm(request.POST)
        current_user = request.user
        if form.is_valid():
            year = form.cleaned_data["year"]
            if not year:
                year = datetime.now().year
            month = form.cleaned_data["month"]
            print(month)
            sales = Sale.objects.filter(datelogged__month=month, datelogged__year=year)
            if not Sale.objects.filter(datelogged__month=month, datelogged__year=year, salecredit=current_user).exists():
                return render(request, "saletracker/index.html", {
            "message": "No sales logged",
            "form": LogSaleForm(),
            "date": DateForm(),
            })
            total_sales = sales.count()
            # Calculate appropriate volume bonus and commission rate
            # // Fixed bug where payplans weren't filtered by user
            payplan = Payplan.objects.filter(user_id=current_user)
            bonus = VolumeBonus.objects.all()
            bonus = bonus.filter(sales_required__lte=total_sales).order_by('-bonus').first().bonus
            comm_rate = payplan.filter(totalsales__lte=total_sales).order_by('-commission').first().commission
            # Create variable for flat model querysets
            flat = Flat.objects.all()
            # Find appropriate flat amount, and seperate sales by sales whose profits * commission rate exceed the flat amount for sale
            flat = flat.filter(sales_required__lte=total_sales).order_by('-flat_amount').first().flat_amount
            payable_amount = 0
            flat_count = 0
            flat_sum = 0
            payable_profit = 0
            for sale in sales:
                if (sale.profit * (comm_rate / 100)) < flat:
                    payable_amount += flat
                    flat_count += 1
                    flat_sum += flat
                else:
                    payable_profit += sale.profit
            total_profit = payable_profit * 100
            # Calculate payable amount by current dollar amount in flats with total profit * commission percent, plus bonus for units sold
            payable_amount += ((total_profit * (comm_rate / 100)) / 100) + bonus
            # Calculate average earned per sale
            payable_average = sales.aggregate(Avg('profit'))
            payable_average = payable_average['profit__avg']
            total_profit = total_profit / 100
            comm_from_profit = payable_amount - flat_sum
            return render(request, "saletracker/index.html", {
                "sales": sales,
                "commission": format(comm_from_profit, ".2f"),
                "bonus": bonus,
                "total_sold": total_sales,
                "avg_earned": format(payable_average, ".2f"),
                "flat_count": flat_count,
                "flat_sum": flat_sum,
                "comm_rate": comm_rate,
                "earnings": format(payable_amount, ".2f"),
                "form": LogSaleForm(),
                "date": DateForm()
            })
    
    if  request.method == "GET":
        # Get current user object from logged in user and filter Sale model by sales credited to user's id
        month = datetime.now().month
        year = datetime.now().year
        current_user = request.user
        sales = Sale.objects.filter(salecredit=current_user.id, datelogged__month=month, datelogged__year=year)
        print(sales)
        if not sales:
            return render(request, "saletracker/index.html", {
            "message": "No sales logged",
            "form": LogSaleForm(),
            "date": DateForm(),
            })
        total_sales = sales.count()
        payable_average = sales.aggregate(Avg('profit'))
        payable_average = payable_average['profit__avg']
        # Calculate appropriate volume bonus and commission rate
        payplan = Payplan.objects.filter(user_id=current_user)
        print(payplan)
        if not payplan:
            return render(request, "saletracker/index.html", {
                "sales": sales,
                "total_sold": total_sales,
                "avg_earned": format(payable_average, ".2f"),
                "form": LogSaleForm(),
                "date": DateForm()
            })
        
        bonus = VolumeBonus.objects.all()
        bonus = bonus.filter(sales_required__lte=total_sales).order_by('-bonus').first().bonus
        comm_rate = payplan.filter(totalsales__lte=total_sales).order_by('-commission').first().commission
        # Create variable for flat model querysets
        flat = Flat.objects.all()
        # Find appropriate flat amount, and seperate sales by sales whose profits * commission rate exceed the flat amount for sale
        flat = flat.filter(sales_required__lte=total_sales).order_by('-flat_amount').first().flat_amount
        payable_amount = 0
        flat_count = 0
        flat_sum = 0
        payable_profit = 0
        for sale in sales:
            if (sale.profit * (comm_rate / 100)) < flat:
                payable_amount += flat
                flat_count += 1
                flat_sum += flat
            else:
                payable_profit += sale.profit
        total_profit = payable_profit * 100
        # Calculate payable amount by current dollar amount in flats with total profit * commission percent, plus bonus for units sold
        payable_amount += ((total_profit * (comm_rate / 100)) / 100) + bonus
        # Calculate average earned per sale
        payable_average = sales.aggregate(Avg('profit'))
        payable_average = payable_average['profit__avg']
        total_profit = total_profit / 100
        return render(request, "saletracker/index.html", {
            "profit": format(total_profit, ".2f"),
            "sales": sales,
            "commission": format(payable_amount, ".2f"),
            "bonus": bonus,
            "total_sold": total_sales,
            "avg_earned": format(payable_average, ".2f"),
            "flat_count": flat_count,
            "flat_sum": flat_sum,
            "comm_rate": comm_rate,
            "earnings": format(payable_amount + bonus, ".2f"),
            "form": LogSaleForm(),
            "date": DateForm()
        })
def log(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    if request.method == "GET":
        return render(request, "saletracker/log.html", {
            "form": LogSaleForm()
        })
    if request.method == "POST":
        form = LogSaleForm(request.POST)
        if form.is_valid():
            profit = form.cleaned_data["profit"]
            username = request.user
            entry = Sale(profit=profit, salecredit=username)
            entry.save()
            return redirect("/saletracker")
def remove_log(request, pk):
    if request.method == "POST":
        current_user = request.user
        sales = Sale.objects.filter(salecredit=current_user.id, id=pk)
        sales.delete()
        return redirect("/saletracker/")
    return render(request, "saletracker/index.html")

    
    

saletracker/templates/saletracker/index.html
{% extends "saletracker/layout.html" %}
{% block body %}
<form action="{% url 'saletracker:index' %}" method="post" class="mb-3">
    {% csrf_token %}
        {{ date }}
    <button type="submit" class="btn btn-primary">Filter</button>
</form>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Profit</th>
                    <th scope="col">Sold By</th>
                    <th scope="col">Log Date</th>
                    <th scope="col">Delete Log</th>
                </tr>
            </thead>
            <tbody>
            {% for sale in sales %}
        <tr>
            <td>${{ sale.profit }}</td>
            <td>{{ sale.salecredit }}</td>
            <td>{{ sale.datelogged }}</td>
            <td>
                <form action="{% url 'saletracker:log_delete' pk=sale.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            </td>    
        </tr>
        {% empty %}
        <h1>{{ message }}</h1>
        {% endfor %}
    </tbody>
    </table>
    
    
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Sales Summary</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Total sales</th>
                <td>{{ total_sold }}</td>
            </tr>
            <tr>
                <th scope="row">Average profit per sale</th>
                <td>${{ avg_earned }}</td>
            </tr>
            <tr>
                <th scope="row">Number of flats</th>
                <td>{{ flat_count }}</td>
            </tr>
            <tr>
                <th scope="row">Sum of flats</th>
                <td>${{ flat_sum }}</td>
          </tr>
          <tr>
              <th scope="row">Commission rate</th>
              <td>{{ comm_rate }}%</td>
            </tr>
            <tr>
              <th scope="row">Volume bonus</th>
              <td>${{ bonus }}</td>
            </tr>
          <tr>
            <th scope="row">Total earnings</th>
            <td>${{ earnings }}</td>
          </tr>
        </tbody>
      </table>
    <form action="{% url 'saletracker:log' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">Log Sale</button>
    <br>
    <a href="{% url 'users:logout' %}">Logout</a>
    <a href="{% url 'saletracker:log' %}">Log sale</a>
    <a href="{% url 'payplan:index' %}">Edit payplan</a>
{% endblock %}

saletracker/templates/saletracker/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Saletracker{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">Paytracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link" aria-current="page" href="{% url 'homepage:index' %}">Home</a>
              <a class="nav-link" aria-current="page" href="{% url 'payplan:index' %}">Payplan</a>
              <a class="nav-link active" aria-current="page" href="{% url 'saletracker:index' %}">Saletracker</a>
              {% if user.is_authenticated %}
              <a class="nav-link" aria-current="page" href="{% url 'users:index' %}">Account info</a>
              <a class="nav-link" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
              {% endif %}
              {% if not user.is_authenticated %}
              <a class="nav-link" aria-current="page" href="{% url 'users:register' %}">Sign Up</a>
              <a class="nav-link" aria-current="page" href="{% url 'users:index' %}">Login</a>
              {% endif %}
            </div>
        </div>
      </div>
    </nav>
    <br><br>
            
        
    <div class="container">
        {% block body %}
        {% endblock %}
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

saletracker/templates/saletracker/log.html
{% extends "saletracker/layout.html" %}
{% block body %}
    <h1>Log a Sale</h1>
    <form action="{% url 'saletracker:log' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Log">
        <a href="{% url 'saletracker:index' %}">Sale Sheet</a>
        <a href="{% url 'saletracker:log' %}">Log sale</a>
    </form>
{% endblock %}