homepage/urls.py
from django.urls import path
from . import views
app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index")
]

payplan/urls.py
from django.urls import path

from . import views

app_name = 'payplan'
urlpatterns = [
    path('', views.index, name="index"),
    path('select', views.select_payplan, name="select"),
    path('add', views.add_payplan, name="add"),
    path('add/scaling', views.add_level, name="add-level"),
    path('edit', views.add_level, name="edit"),
    path('edit/<int:pk>', views.update_payplan, name="update"),
    path('flat', views.add_flat, name="flat"),
    path('volume-bonus', views.add_volume_bonus, name="volume-bonus")
]

paytracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls")),
    path('payplan/', include("payplan.urls")),
    path('users/', include("users.urls")),
    path('saletracker/', include("saletracker.urls"))
]

saletracker/urls.py
from django.urls import path
from . import views

app_name = 'saletracker'

urlpatterns = [
    path("", views.index, name="index"),
    path('log', views.log, name="log"),
    path('<int:pk>', views.remove_log, name="log_delete")
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('register', views.register_view, name="register")
]

payplan/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
User = get_user_model()
from datetime import datetime
# Create your models here.
# Join models on unit count after a users model has been created

class Sale(models.Model):
    profit = models.IntegerField()
    salecredit = models.ForeignKey(User, on_delete=models.CASCADE)
    datelogged = models.DateField(default=datetime.now)

    def __str__(self):
        return f"Profit: ${self.profit} Credit:{self.salecredit} Date:{self.datelogged}"
    
class Payplan(models.Model):
    commission = models.IntegerField(default=0)
    totalsales = models.IntegerField(default=0)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        if self.totalsales != 0:
            return f"{self.commission}% commission per sale after {self.totalsales} sales."
        else:
            return f"{self.commission}% base commission"

class VolumeBonus(models.Model):
    bonus = models.IntegerField(default=0)
    sales_required = models.IntegerField(default=0)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    class Meta:
        verbose_name_plural = "volume bonuses"
    
    def __str__(self):
        return  f"${self.bonus} bonus for {self.sales_required} sales."

class Flat(models.Model):
    flat_amount = models.IntegerField(default=0)
    sales_required = models.IntegerField(default=0, blank=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    def __str__(self):
        if self.sales_required != 0:
            return  f"${self.flat_amount} flat after {self.sales_required} sales."
        else:
            return f"${self.flat_amount} flats"
class UserModel(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    email = models.EmailField()
    store_code = models.CharField(max_length=50)
    def __str__(self):
        return  f"First name: {self.first_name} Last name: {self.last_name} Username: {self.username} Email: {self.email} Store code: {self.store_code}"
    

class SaleSummary(models.Model):
    # Foreign key to link user with their summary
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    year = models.IntegerField()
    month = models.IntegerField()
    
    sale_count = models.IntegerField()
    
    profit_sum = models.IntegerField()
    profit_avg = models.DecimalField(decimal_places=2, max_digits=100)

    flat_count = models.IntegerField()
    flat_sum = models.IntegerField()

    commission_rate = models.IntegerField()
    commission_earnings = models.IntegerField()

    volume_bonus = models.IntegerField()

    earnings_total = models.DecimalField(decimal_places=2, max_digits=100)

#Need a foreign key to join sales table with users table to determine which person gets credit for a sale
#Write a loop in a view to calculate commission if user sales are greater than totalsales in Payplan model

payplan/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from datetime import datetime

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    store_code = forms.CharField(max_length=10)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'store_code', 'password1', 'password2')
class LogSaleForm(forms.Form):
    profit = forms.IntegerField()
    
class RegisterPayplan(forms.Form):
    base_commission = forms.IntegerField()
    
class ScalingPayplan(forms.Form):
    commission_bump = forms.IntegerField()
    for_units_sold = forms.IntegerField()

class VolumeBonusForm(forms.Form):
    volume_bonus = forms.IntegerField(help_text="Enter total amount of volume bonus after hitting milestone")
    for_units_sold = forms.IntegerField(help_text="Sales required for bonus")

class FlatForm(forms.Form):
    flat_amount = forms.IntegerField()
    sales_required = forms.IntegerField(help_text="If flat amount does not scale with sales enter '0'")

class DateForm(forms.Form):
    choices = [
        (1, "January"),
        (2, "February"),
        (3, "March"),
        (4, "April"),
        (5, "May"),
        (6, "June"),
        (7, "July"),
        (8, "August"),
        (9, "September"),
        (10, "October"),
        (11, "November"),
        (12, "December")
    ]
    current_month = datetime.now().month
    current_year = datetime.now().year
    for i in choices:
        if current_month in i:
            current_month = i
    print(current_month)
    year = forms.IntegerField(required=False, initial=current_year)
    month = forms.ChoiceField(choices=choices, initial=current_month)

'''class SaleSummaryForm(forms.Form):
    
    profit = forms.DecimalField()
    sales = forms.IntegerField()
    commission = forms.DecimalField()
    bonus = forms.IntegerField()
    total_sold = forms.IntegerField()
    avg_earned = forms.DecimalField()
    flat_total = forms.IntegerField()
    flat_sum = forms.IntegerField()
    comm_percent = forms.IntegerField()
    earnings = forms.DecimalField()'''

payplan/views.py
from django.shortcuts import render
from . models import Payplan, Flat, VolumeBonus
from django.http import HttpResponseRedirect
from django.urls import reverse
from payplan.forms import RegisterPayplan, ScalingPayplan, FlatForm, VolumeBonusForm
# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    current_user = request.user
    payplan = Payplan.objects.filter(user_id=current_user)
    flat = Flat.objects.filter(user_id=current_user)
    volume_bonus = VolumeBonus.objects.filter(user_id=current_user)
    if not payplan:
        if not flat:
            if not volume_bonus:
                return render(request, "payplan/payplan-select.html", {
                    "message": "No payplan saved"
                })
    return render(request, "payplan/index.html", {
        "payplan": payplan,
        "flat": flat,
        "volume_bonus": volume_bonus,
    })

def select_payplan(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "payplan/payplan-select.html")

def add_payplan(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if request.method == "GET":
        current_user = request.user
        payplan = Payplan.objects.filter(user_id=current_user)
        print(payplan)
        if payplan:
            return render(request, "payplan/scale-payplan.html", {
                "payplan": payplan,
                "form": ScalingPayplan()
            })
        return render(request, "payplan/add-payplan.html", {
            "comm_form": RegisterPayplan()
        })
    if request.method == "POST":
        form = RegisterPayplan(request.POST)
        if form.is_valid():
            commission = form.cleaned_data["base_commission"]
            current_user = request.user
            entry_commission = Payplan(commission=commission, user_id=current_user)
            entry_commission.save()
            return HttpResponseRedirect(reverse("payplan:index"))
def add_level(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    current_user = request.user
    if request.method == "POST":
        form = ScalingPayplan(request.POST)
        if form.is_valid():
            commission = form.cleaned_data["commission_bump"]
            units = form.cleaned_data["for_units_sold"]
            entry = Payplan(commission=commission, totalsales=units, user_id=current_user)
            entry.save()
            return HttpResponseRedirect(reverse("payplan:index"))
    return render(request, "payplan/edit.html", {
        "payplan": Payplan.objects.filter(user_id=current_user),
        "message": "No payplans saved"
    })
    
def update_payplan(request, pk):
    if request.method == "GET":
        current_user = request.user
        return render(request, "payplan/update-entry.html", {
            "payplan": Payplan.objects.filter(user_id=current_user, id=pk),
            "form": ScalingPayplan(),
            "message": "No payplans saved"
        })
    if request.method == "POST":
        if 'remove' in request.POST:
            current_user = request.user
            Payplan.objects.filter(id=pk).delete()
            return HttpResponseRedirect(reverse("payplan:edit"))
        elif 'update' in request.POST:
            form = ScalingPayplan(request.POST)
            if form.is_valid():
                commission = form.cleaned_data["commission_bump"]
                units = form.cleaned_data["for_units_sold"]
                Payplan.objects.filter(id=pk).update(commission=commission, totalsales=units)
                return HttpResponseRedirect(reverse("payplan:edit"))
def add_flat(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if request.method == "GET":
        return render(request, "payplan/add-flat.html", {
            "form": FlatForm()
        })
    if request.method == "POST":
        form = FlatForm(request.POST)
        if form.is_valid():
            current_user = request.user
            flat = form.cleaned_data["flat_amount"]
            sales_required = form.cleaned_data["sales_required"]
            entry = Flat(flat_amount=flat, sales_required=sales_required, user_id=current_user)
            entry.save()
            return HttpResponseRedirect(reverse("payplan:index"))
def add_volume_bonus(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if request.method == "GET":
        return render(request, "payplan/add-volume-bonus.html", {
            "form": VolumeBonusForm()
        })
    if request.method == "POST":
        form = VolumeBonusForm(request.POST)
        if form.is_valid():
            current_user = request.user
            volume_bonus = form.cleaned_data["volume_bonus"]
            sales_required = form.cleaned_data["for_units_sold"]
            entry = VolumeBonus(bonus=volume_bonus, sales_required=sales_required, user_id=current_user)
            entry.save()
            return HttpResponseRedirect(reverse("payplan:index"))

payplan/templates/payplan/add-flat.html
{% extends "payplan/layout.html" %}
{% block body %}
<div class="form-group">
<form action="{% url 'payplan:flat' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_flat_amount">Flat amount:</label>
        <input type="number" class="form-control" name="flat_amount" autofocus required id="id_flat_amount">
        <br>
    </div>
    <div class="mb-3">
        <label for="id_sales_required">Sales required:</label>
        <input type="number" class="form-control" name="sales_required" required id="id_sales_required">
        <br>
        <span class="helptext" style="color:rgb(0, 140, 255);"><ul><li>If flat does not scale with sales enter 0.</li></ul></span>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Add</button>
</form>
</div>
{% endblock %}

payplan/templates/payplan/add-payplan.html
{% extends "payplan/layout.html" %}
{% block body %}
<div class="form-group">
<form action="{% url 'payplan:add' %}" method="post">
    {% csrf_token %}
    {{ comm_form.as_p }}
    {{ flat_form.as_p }}
    <button type="submit" class="btn btn-primary">Add</button>
</form>
</div>
{% endblock %}

payplan/templates/payplan/add-volume-bonus.html
{% extends "payplan/layout.html" %}
{% block body %}
<div class="form-group">
    <form action="{% url 'payplan:volume-bonus' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_volume_bonus">Volume bonus:</label>
            <input type="number" class="form-control" name="volume_bonus" autofocus required id="id_volume_bonus">
            <span class="helptext" style="color:rgb(0, 140, 255);">
                <ul>
                    <li>Enter total bonus for units sold.</li>
                    <li>Ex: If you receive $250 for 10 sales and an additional $250 for 12 sales, you would enter $500 for 12 sales.</li>
                </ul>
            </span>
            <br>
        </div>
        <div class="mb-3">
            <label for="id_for_units_sold">For units sold:</label>
            <input type="number" class="form-control" name="for_units_sold" required id="id_for_units_sold">
            <br>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
    </div>
{% endblock %}

payplan/templates/payplan/edit.html
{% extends "payplan/layout.html" %}
{% block body %}
{% for entry in payplan %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Payplan details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Commission % per sale</th>
            <td>{{ entry.commission }}</td>
        </tr>
        <tr>
            <th scope="row">Sales required</th>
            <td>{{ entry.totalsales }}+</td>
        </tr>
        <tr>
            <th scope="row"></th>
            <td>
                <form action="{% url 'payplan:update' pk=entry.id %}" method="get">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-warning">Edit</button>
                </form>
            </td>
        </tr>
        {% empty %}
        {{ message }}
        <a href="{% url 'payplan:add' %}">Add payplan</a>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

payplan/templates/payplan/index.html
{% extends "payplan/layout.html" %}

{% block body %}
    <h1>Payplan</h1>
    <ul>
        <h3>
        {% for i in payplan %}
        <li>{{ i }}</li>
        {% endfor %}
        {% for j in flat %}
        <li>{{ j }}</li>
        {% endfor %}
        {% for k in volume_bonus %}
        <li>{{ k }}</li>
        {% endfor %}
    </h3>
    </ul>
    <h5>
        <a href="{% url 'payplan:add' %}" class="btn btn-primary">Add a payplan or add scaling</a>
        <a href="{% url 'payplan:volume-bonus' %}" class="btn btn-primary">Add a volume bonus</a>
        <a href="{% url 'payplan:flat' %}" class="btn btn-primary">Add a flat payable amount</a>
        <a href="{% url 'payplan:add-level' %}" class="btn btn-primary">Edit payplan</a>
</h5>
{% endblock %}

payplan/templates/payplan/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
      Payplan
  {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">Paytracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link" aria-current="page" href="{% url 'homepage:index' %}">Home</a>
              <li class="nav-item dropdown">
                <a href="{% url 'payplan:index' %}" class="nav-link dropdown-toggle active" aria-current="page" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Payplan
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'payplan:add' %}">Add a payplan or scaling</a></li>
                  <li><a class="dropdown-item" href="{% url 'payplan:volume-bonus' %}">Add a volume bonus</a></li>
                  <li><a class="dropdown-item" href="{% url 'payplan:flat' %}">Add a flat commission amount</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'payplan:add-level' %}">Edit payplan</a></li>
                </ul>
              </li>
              <a class="nav-link" aria-current="page" href="{% url 'saletracker:index' %}">Saletracker</a>
              {% if user.is_authenticated %}
              <a class="nav-link" aria-current="page" href="{% url 'users:index' %}">Account info</a>
              <a class="nav-link" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
              {% endif %}
              {% if not user.is_authenticated %}
              <a class="nav-link" aria-current="page" href="{% url 'users:register' %}">Sign Up</a>
              <a class="nav-link" aria-current="page" href="{% url 'users:index' %}">Login</a>
              {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <br><br>
    <div class="container">
        {% block body %}
        {% endblock %}
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

payplan/templates/payplan/payplan-select.html
{% extends "payplan/layout.html" %}
{% block body %}
<h1>{{ message }}</h1>
<a href="{% url 'payplan:add' %}" class="btn btn-primary">Add a payplan or add scaling</a>
<a href="{% url 'payplan:volume-bonus' %}" class="btn btn-primary">Add a volume bonus</a>
<a href="{% url 'payplan:flat' %}" class="btn btn-primary">Add a flat payable amount</a>
<a href="{% url 'payplan:add-level' %}" class="btn btn-primary">Edit payplan</a>
{% endblock %}

payplan/templates/payplan/scale-payplan.html
{% extends "payplan/layout.html" %}
{% block body %}
{% for entry in payplan %}
<h3>{{ entry }}</h3>
{% endfor %}
<form action="{% url 'payplan:add-level' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ flat_form.as_p}}
    <button type="submit" class="btn btn-primary">Add next level</button>
</form>
{% endblock %}

payplan/templates/payplan/update-entry.html
{% extends "payplan/layout.html" %}
{% block body %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Payplan details</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in payplan %}
        <tr>
            <th scope="row">Commission % per sale</th>
            <td>{{ entry.commission }}</td>
        </tr>
        <tr>
        <th scope="row">Sales required</th>
        <td>{{ entry.totalsales }}</td>
        </tr>
    </tbody>
</table>
<form action="{% url 'payplan:update' pk=entry.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success" name="update">Save</button>
</form>
<form action="{% url 'payplan:update' pk=entry.id %}" method="post"> 
    {% csrf_token %}
    <button type="submit" class="btn btn-danger" name="remove">Delete</button>
</form>   
{% empty %}
{% endfor %}
{% endblock %}