homepage/urls.py
from django.urls import path
from . import views
app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index")
]

payplan/urls.py
from django.urls import path

from . import views

app_name = 'payplan'
urlpatterns = [
    path('', views.index, name="index"),
    path('select', views.select_payplan, name="select"),
    path('add', views.add_payplan, name="add"),
    path('add/scaling', views.add_level, name="add-level"),
    path('edit', views.add_level, name="edit"),
    path('edit/<int:pk>', views.update_payplan, name="update"),
    path('flat', views.add_flat, name="flat"),
    path('volume-bonus', views.add_volume_bonus, name="volume-bonus")
]

paytracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls")),
    path('payplan/', include("payplan.urls")),
    path('users/', include("users.urls")),
    path('saletracker/', include("saletracker.urls"))
]

saletracker/urls.py
from django.urls import path
from . import views

app_name = 'saletracker'

urlpatterns = [
    path("", views.index, name="index"),
    path('log', views.log, name="log"),
    path('<int:pk>', views.remove_log, name="log_delete")
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('register', views.register_view, name="register")
]

users/models.py
from django.db import models

# Create your models here.

payplan/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from datetime import datetime

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    store_code = forms.CharField(max_length=10)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'store_code', 'password1', 'password2')
class LogSaleForm(forms.Form):
    profit = forms.IntegerField()
    
class RegisterPayplan(forms.Form):
    base_commission = forms.IntegerField()
    
class ScalingPayplan(forms.Form):
    commission_bump = forms.IntegerField()
    for_units_sold = forms.IntegerField()

class VolumeBonusForm(forms.Form):
    volume_bonus = forms.IntegerField(help_text="Enter total amount of volume bonus after hitting milestone")
    for_units_sold = forms.IntegerField(help_text="Sales required for bonus")

class FlatForm(forms.Form):
    flat_amount = forms.IntegerField()
    sales_required = forms.IntegerField(help_text="If flat amount does not scale with sales enter '0'")

class DateForm(forms.Form):
    choices = [
        (1, "January"),
        (2, "February"),
        (3, "March"),
        (4, "April"),
        (5, "May"),
        (6, "June"),
        (7, "July"),
        (8, "August"),
        (9, "September"),
        (10, "October"),
        (11, "November"),
        (12, "December")
    ]
    current_month = datetime.now().month
    current_year = datetime.now().year
    for i in choices:
        if current_month in i:
            current_month = i
    print(current_month)
    year = forms.IntegerField(required=False, initial=current_year)
    month = forms.ChoiceField(choices=choices, initial=current_month)

'''class SaleSummaryForm(forms.Form):
    
    profit = forms.DecimalField()
    sales = forms.IntegerField()
    commission = forms.DecimalField()
    bonus = forms.IntegerField()
    total_sold = forms.IntegerField()
    avg_earned = forms.DecimalField()
    flat_total = forms.IntegerField()
    flat_sum = forms.IntegerField()
    comm_percent = forms.IntegerField()
    earnings = forms.DecimalField()'''

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from payplan.models import Sale, Payplan, UserModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.db.models import Sum
from payplan.forms import RegisterUserForm

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    account_info = UserModel.objects.filter(username=request.user.username)
    return render(request, "users/index.html", {
        "account_info": account_info
    })
def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:index"))
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
    
        if user:
            login(request, user)
            if Payplan.objects.filter(user_id=user).exists():
                return HttpResponseRedirect(reverse("saletracker:index"))
            else:
                return HttpResponseRedirect(reverse("payplan:index"))
        else:
            return render(request, "users/login.html", {
                "message": "invalid login"
            })
 
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "logged out"
    })

def register_view(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            store_code = form.cleaned_data['store_code']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Registration successful"))
            user_entry = UserModel(username=username, first_name=first_name, last_name=last_name, email=email, store_code=store_code)
            user_entry.save()
            return HttpResponseRedirect(reverse("payplan:index"))
    else:
        form = RegisterUserForm()
    return render(request, "users/register.html", {
        "form": form
    })

users/templates/users/index.html
{% extends "users/layout.html" %}
{% block body %}
{% for entry in account_info %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Account info</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="col">Username</th>
            <td>{{ entry.username }}</td>
        </tr>
        <tr>
            <th scope="col">First name</th>
            <td>{{ entry.first_name }}</td>
        </tr>
        <tr>
            <th scope="col">Last name</th>
            <td>{{ entry.last_name }}</td>
        </tr>
        <tr>
            <th scope="col">Email</th>
            <td>{{ entry.email }}</td>
        </tr>
        <tr>
            <th scope="col">Store code</th>
            <td>{{ entry.store_code }}</td>
        </tr>
    </tbody>
</table>
{% endfor %}
{% endblock %}

users/templates/users/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">Paytracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link" aria-current="page" href="{% url 'homepage:index' %}">Home</a>
              <a class="nav-link" aria-current="page" href="{% url 'payplan:index' %}">Payplan</a>
              <a class="nav-link" aria-current="page" href="{% url 'saletracker:index' %}">Saletracker</a>
              {% if user.is_authenticated %}
              <a class="nav-link" aria-current="page" href="{% url 'users:index' %}">Account info</a>
              <a class="nav-link" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
              {% endif %}
              {% if not user.is_authenticated %}
              <a class="nav-link" aria-current="page" href="{% url 'users:register' %}">Sign Up</a>
              <a class="nav-link" aria-current="page" href="{% url 'users:index' %}">Login</a>
              {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <br><br>
    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}
{% block body %}
    
    {% if message %}
    <div class="alert alert-success" role="alert">
    
    {{ message }}
    </div>
    {% endif %}
    <div class="form-group">
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <input type="text" class="form-control" name="username" placeholder="Username">
          </div>
          <div class="mb-3">
            <input type="password" class="form-control" name="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
        
    </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "users/layout.html" %}
{% block body %}
    
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="form-group">
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <h3>All fields are required</h3>
            <label for="id_username" class="form-label">Username</label>
            <input type="text" class="form-control" name="username" autofocus required id="id_username">
            <br>
            <span class="helptext" style="color:rgb(0, 140, 255);"><ul><li>150 characters or fewer. Letters, digits and @/./+/-/_ only.</li></ul></span>
          </div>
          <div class="mb-3">
            <label for="id_first_name" class="form-label">First name</label>
            <input type="text" class="form-control" name="first_name" required id="id_first_name">
          </div>
          <div class="mb-3">
            <label for="id_last_name" class="form-label">Last name</label>
            <input type="text" class="form-control" name="last_name" required id="id_last_name">
          </div>
          <div class="mb-3">
            <label for="id_email" class="form-label">Email</label>
            <input type="email" class="form-control" name="email" required id="id_email">
          </div>
          <div class="mb-3">
            <label for="id_store_code" class="form-label">Store code</label>
            <input type="text" class="form-control" name="store_code" required id="id_store_code">
          </div>
          <div class="mb-3">
            <label for="id_password1" class="form-label">Password</label>
            <input type="password" class="form-control" name="password1" required id="id_password1" autocomplete="new-password">
            <span class="helptext" style="color:rgb(0, 140, 255);"><ul><li>Your password cannot be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul></span>
          </div>
          <div class="mb-3">
            <label for="id_password2" class="form-label">Password confirmation</label>
            <input type="password" class="form-control" name="password2" required id="id_password2">
            <br>
            <span class="helptext" style="color:rgb(0, 140, 255);"><ul><li>Enter the same password as before, for verification.</li></ul></span>
          </div>
          <br>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
{% endblock %}

users/templates/users/salesheet.html
{% extends "users/layout.html" %}
{% block title %}Salesheet{% endblock %}
{% block body %}
    <h1>Logged in</h1>    
    <div>This is the salesheet</div>
    <div>Total sales: ${{ profit }}</div>
    {% for sale in sales %}
    <ul>
        <li>{{ sale }}</li>
    </ul>
    {% endfor %}
    <div>Commission earned: ${{ commission }}</div>
    <div>Total sales: {{ total_sold }}</div>
    <div>Average commission per sale: ${{ avg_earned }}</div>
    <div>Commission rate: {{ comm_rate }}%</div>
    <a href="{% url 'users:logout' %}">Logout</a>
{% endblock %}